
version: '3.7'

services:
  web:
    build: .
    working_dir: /home/fastapi/web
    command: "uvicorn main:app --host 0.0.0.0 --port 8080"
    volumes:
      - ./backend:/home/fastapi/web
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: "postgres:12.0-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: un!bz1nf0S3c
    ports:
      - "5432:5432"

  pgadmin:
     image: dpage/pgadmin4
     restart: always
     environment:
       PGADMIN_DEFAULT_EMAIL: sbhuiyan@unibz.it
       PGADMIN_DEFAULT_PASSWORD: admin1234
       PGADMIN_LISTEN_PORT: 80
     ports:
       - "80:80"
     volumes:
       - pgadmin-data:/var/lib/pgadmin
      
volumes:
  pgadmin-data:
  postgres_data:
           

